<a href="https://colab.research.google.com/github/nisha1365/NLP_Basics-krishnaik/blob/main/Word_Embedding_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding Techniques using Embedding Layer in Keras

In [5]:
from keras.preprocessing.text import one_hot

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size = 10000

# One Hot representation

In [7]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
[print(one_hot)]


<function one_hot at 0x7f072a154ca0>


[None]

# Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2635 5661 1061 6654]
 [   0    0    0    0 2635 5661 1061 3547]
 [   0    0    0    0 2635 4361 1061 8234]
 [   0    0    0 9095 2762 1717 5551 5789]
 [   0    0    0 9095 2762 1717 5551  283]
 [   0    0    0 8352 2635 3811 1061  441]
 [   0    0    0    0 4178 6851 9766 5551]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 153ms/step
[[[-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815
   -0.02519836  0.04052723 -0.02145087  0.00923487  0.02007875]
  [-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815
   -0.02519836  0.04052723 -0.02145087  0.00923487  0.02007875]
  [-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815
   -0.02519836  0.04052723 -0.02145087  0.00923487  0.02007875]
  [-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815
   -0.02519836  0.04052723 -0.02145087  0.00923487  0.02007875]
  [-0.04417664 -0.00625084 -0.04519552 -0.02483777 -0.03341445
    0.04261644 -0.01748532  0.0322865   0.03892099 -0.02403934]
  [-0.00935954 -0.01472308  0.04826731 -0.01804324  0.02302326
    0.04201739 -0.03641888 -0.02592943  0.02201445 -0.04495341]
  [ 0.02812824 -0.02407708  0.01042937 -0.00305195  0.00132415
   -0.01069901  0.03945274 -0.0129124   0.02673936  0.01136438]
  [-0.0138535  -0.0457432   0.00805664 -0.01020456  0.0481

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 2635, 5661, 1061, 6654], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 22ms/step
[[-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815 -0.02519836
   0.04052723 -0.02145087  0.00923487  0.02007875]
 [-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815 -0.02519836
   0.04052723 -0.02145087  0.00923487  0.02007875]
 [-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815 -0.02519836
   0.04052723 -0.02145087  0.00923487  0.02007875]
 [-0.01457775 -0.03112534 -0.02442366  0.02163656 -0.04805815 -0.02519836
   0.04052723 -0.02145087  0.00923487  0.02007875]
 [-0.04417664 -0.00625084 -0.04519552 -0.02483777 -0.03341445  0.04261644
  -0.01748532  0.0322865   0.03892099 -0.02403934]
 [-0.00935954 -0.01472308  0.04826731 -0.01804324  0.02302326  0.04201739
  -0.03641888 -0.02592943  0.02201445 -0.04495341]
 [ 0.02812824 -0.02407708  0.01042937 -0.00305195  0.00132415 -0.01069901
   0.03945274 -0.0129124   0.02673936  0.01136438]
 [-0.0138535  -0.0457432   0.00805664 -0.01020456  0.04814046 -0.01237391